// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "London",
  "venue": "The Stafford London, 16-18 St James's Place, London SW1A 1NJ",
  "capacity": 30,
  "eventTitle": "VIP Connect — London Leadership Dinner",
  "heroImageUrl": "https://zxjuq10yjr13vx51.public.blob.vercel-storage.com/photos/moloco-event-london-2/winecellar.jpg",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "London Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Thirty leaders.\\nSeventeenth-century wine cellars.\\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other's assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What's working, what's not, and what the next twelve months look like.",
    "We gather in The Stafford London's historic wine cellars, carved from 17th-century foundations beneath St James's."
  ],
  "agendaItems": [
    {
      "time": "6:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "6:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "6:45 PM",
      "title": "Dinner",
      "description": "Sommelier-led wine tasting with Michelin-starred cuisine in historic underground cellars, featuring new Moloco x BCG research and fireside conversations."
    },
    {
      "time": "9:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "6:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "6:30 PM",
      "label": "Executive session"
    },
    {
      "time": "6:45 PM",
      "label": "Dinner"
    },
    {
      "time": "9:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 30 people. Small enough that everyone speaks, diverse enough that you'll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you'd wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "The Stafford London, 16-18 St James's Place, London SW1A 1NJ accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they'll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — London Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-london-2.vercel.app",
  "slug": "moloco-event-london-2",
  "eventSubtitle": "An invitation-only evening for senior FinTech marketing leaders",
  "venueAddress": "16-18 St James's Place, SW1A 1NJ, London",
  "venueAddressFull": "16-18 St James's Place, London SW1A 1NJ, United Kingdom",
  "date": "May 14, 2026",
  "dateFull": "Wednesday, May 14",
  "dateISO": "2026-05-14",
  "calendarDateStart": "20260514T180000",
  "calendarDateEnd": "20260514T210000",
  "time": "6:00 PM",
  "timezone": "Europe/London",
  "timezoneAbbr": "BST",
  "venueDescription": "The Stafford London stands as one of Mayfair's most distinguished hotels, occupying a tranquil position on historic St James's Place. The hotel's legendary wine cellars, carved from 17th-century foundations, house one of London's finest collections and provide an atmospheric setting beneath the bustling streets above. With its blend of British heritage and contemporary luxury, The Stafford offers an intimate backdrop for discerning gatherings.",
  "venueCapacityNote": "The historic wine cellars accommodate thirty guests in an exclusive underground setting.",
  "venueDiningNote": "Michelin-starred cuisine prepared by the hotel's acclaimed culinary team, paired with selections from the legendary cellar.",
  "venueDirections": "The Stafford London is located on St James's Place, a quiet street connecting Piccadilly and St James's Street. Green Park Underground station is a three-minute walk away. Enter through the main hotel reception and our team will escort you to the wine cellars.",
  "venueExperienceLine": "We gather in The Stafford London's historic wine cellars, carved from 17th-century foundations beneath St James's.",
  "dinnerDescription": "Sommelier-led wine tasting with Michelin-starred cuisine in historic underground cellars, featuring new Moloco x BCG research and fireside conversations.",
  "mapsUrl": "https://maps.google.com/maps?q=The+Stafford+London,+16-18+St+James%27s+Place,+London+SW1A+1NJ,+UK"
};